version: '2'

services:
   db:
     image: mongo:3.0.14
     volumes:
       - db_data:/var/lib/mysql
     restart: always

   login:
     depends_on:
       - db
     image: twistlock/login:latest
     ports:
       - "3000:3000" # Map port 3000 to port 3000
     restart: always
     environment:
       CONNECTION_STRING: mongodb://db/myapp
volumes:
    db_data: